export const STYLE_CONFIGS = {
  // Modifiable by theme store
  fontFamily: 'CircularStd',
  backgroundColor: '#ffffff',
  primaryColor: '#F25C24',
  secondaryColor: '#222222',
  tertiaryColor: '#9FBAA8',
  errorColor: '#EC4A53',
  disabledColor: '#EAEAEA',
  linkColor: '#F25C24',
  infoColor: '#27AE60',
  pageTitleColor: '#222222',
  pageSubtitleColor: '#BDBDBD',
  textColor: '#333333',
  subtextColor: '#222222',
  sectionTitleColor: '#333333',
  sectionSubtitleColor: '#878787',
  sectionDetailsBackgroundColor: '#F5F5F5',
  sectionLightBackgroundColor: '#E9E9EA',
  borderColor: '#EAEAED',
  dividerColor: '#DCDCDC',
  warningColor: '#C06800',
  calendarWeekDay: '#848484',
  disabledCalendarDay: '#CBCBCB',
  outsideMonthCalendarDay: '#848484',
  warning: '#E98B1C',
  success: '#0CA16C',

  // Non modifiable
  borderRadius: '4px',
  containerPadding: '24px',
  boxShadow: '0px_4px_14px_rgba(0,0,0,0.08)',
  margins: {
    xs: '4px',
    s: '8px',
    m: '16px',
    l: '32px',
    xl: '64px',
  },
} as const;
